export const projects = [
    {
        id: 1,
        name: '3Cat Gamified Experience',
        href: '#',
        category: 'uxui',
        timeline: '4 months',
        client: 'Corporació Catalana de Mitjans Audiovisuals',
        KeyActivities: ["UX/UI", "Gamification", "Development", "Prototyping"],
        tinDescription:'Design a prototype for improving engagement',
        imageSrc: '/imatges/3cat/portada3Cat.png',
        imageAlt: 'Tall slender porcelain bottle with natural clay textured body and cork stopper.',
    },
    {
        id: 2,
        name: 'BookEcho',
        href: '#',
        category: 'uxui',
        timeline: '4 months',
        client: 'Class project',
        KeyActivities: ["UX/UI", "Gamification", "Development", "Prototyping"],
        tinDescription:'An App to register your readings',
        imageSrc: '/imatges/BookEcho/bookechoCover.png',
        imageAlt: 'Olive drab green insulated bottle with flared screw lid and flat top.',
    },
    {
        id: 3,
        name: 'Nuñez i Navarro Maps',
        href: '#',
        category: 'uxui',
        timeline: '3 months',
        client: 'Nuñez i Navarro',
        KeyActivities: ["UX/UI", "Gamification", "Development", "Prototyping"],
        tinDescription:'Exploring Google Maps Integration in NN pages',
        imageSrc: 'https://tailwindcss.com/plus-assets/img/ecommerce-images/category-page-04-image-card-03.jpg',
        imageAlt: 'Person using a pen to cross a task off a productivity paper card.',
    },
    {
        id: 4,
        name: 'Barcimed',
        href: '#',
        category: 'vdxr',
        timeline: '5 months',
        client: 'Final Degree Project',
        KeyActivities: ["UX/UI", "Gamification", "Development", "Prototyping"],
          tinDescription:'A gamified and immersive experience to discover Medeival Barcelona',
        imageSrc: '/imatges/Barcimed/portadaBarcimed.png',
        imageAlt: 'Hand holding black machined steel mechanical pencil with brass tip and top.',
    },
    {
        id: 5,
        name: 'Masks & Marquises',
        href: '#',
        category: 'vdxr',
        timeline: '4 months',
        client: 'Agència de Patrimoni Cultural de Catalunya',
        KeyActivities: ["UX/UI", "Gamification", "Development", "Prototyping"],
          tinDescription:'VR videogame inspired in the Moja Palace',
        imageSrc: '/imatges/Giravolt/giravoltCover.png',
        imageAlt: 'Paper card sitting upright in walnut card holder on desk.',
    },
    {
        id: 6,
        name: 'Kitchen Hunt',
        href: '#',
        category: 'vdxr',
        timeline: '4 months',
        client: 'Class project',
        KeyActivities: ["UX/UI", "Gamification", "Development", "Prototyping"],
          tinDescription:'A kitchen videogame made in Unity',
        imageSrc: 'https://tailwindcss.com/plus-assets/img/ecommerce-images/category-page-04-image-card-06.jpg',
        imageAlt: 'Stack of 3 small drab green cardboard paper card refill boxes with white text.',
    },
    {
        id: 7,
        name: 'Farmàcia Isabel Tell',
        href: '#',
        category: 'other',
        timeline: '4 months',
        client: 'Farmàcia Isabel Tell',
        KeyActivities: ["UX/UI", "Gamification", "Development", "Prototyping"],
          tinDescription:'Creating the identity of a pharmacy',
        imageSrc: 'https://tailwindcss.com/plus-assets/img/ecommerce-images/category-page-04-image-card-07.jpg',
        imageAlt: 'Brass scissors with geometric design, black steel finger holes, and included upright brass stand.',
    },
    {
        id: 8,
        name: 'Stranger Things Clock',
        href: '#',
        category: 'other',
        timeline: '2 weeks',
        client: 'Class project',
        KeyActivities: ["UX/UI", "Gamification", "Development", "Prototyping"],
          tinDescription:'Animation inspired in Stragner Things',
        imageSrc: 'https://tailwindcss.com/plus-assets/img/ecommerce-images/category-page-04-image-card-08.jpg',
        imageAlt: 'Textured gray felt pouch for paper cards with snap button flap and elastic pen holder loop.',
    },
]